DROP TABLE IF EXISTS CARGO_POLITICO;
DROP TABLE IF EXISTS MIDIA;
DROP TABLE IF EXISTS MEIO_COMUNICACAO;
DROP TABLE IF EXISTS FOTO;
DROP TABLE IF EXISTS ELEITOR;
DROP TABLE IF EXISTS PARTIDO;
DROP TABLE IF EXISTS CANDIDATO;
DROP TABLE IF EXISTS REGIAO;
DROP TABLE IF EXISTS PESSOA;
DROP TABLE IF EXISTS NOTICIA;

CREATE TABLE PESSOA(
  id_pessoa INTEGER PRIMARY KEY AUTO_INCREMENT,
  cpf VARCHAR(20) NOT NULL,
  p_nome VARCHAR(15) NOT NULL,
  u_nome VARCHAR(15) NOT NULL,
  data_nascimento DATE NOT NULL,
  idade INTEGER NOT NULL,
  endereco VARCHAR(120) NOT NULL
);

CREATE TABLE REGIAO(
  id_regiao INTEGER PRIMARY KEY AUTO_INCREMENT,
  nome_regiao VARCHAR(20) NOT NULL,
  num_eleitores INTEGER,
  num_candidatos INTEGER
);

CREATE TABLE ELEITOR(
  id_eleitor INTEGER PRIMARY KEY AUTO_INCREMENT,
  id_pessoa INTEGER NOT NULL,
  id_regiao INTEGER NOT NULL,
  zona VARCHAR(50) NOT NULL,
  secao INTEGER NOT NULL,
  FOREIGN KEY(id_pessoa) REFERENCES PESSOA(id_pessoa),
  FOREIGN KEY(id_regiao) REFERENCES REGIAO(id_regiao)
);

CREATE TABLE CANDIDATO (
  num_id INTEGER PRIMARY KEY AUTO_INCREMENT,
  id_pessoa INTEGER NOT NULL,
  id_regiao INTEGER NOT NULL,
  FOREIGN KEY(id_pessoa) REFERENCES PESSOA(id_pessoa),
  FOREIGN KEY(id_regiao) REFERENCES REGIAO(id_regiao)
);

CREATE TABLE FOTO (
  foto_id INTEGER PRIMARY KEY AUTO_INCREMENT,
  id_pessoa INTEGER NOT NULL,
  nome_foto VARCHAR(50) NOT NULL,
  tamanho_foto INTEGER NOT NULL,
  formato_foto VARCHAR(5) NOT NULL,
  FOREIGN KEY(id_pessoa) REFERENCES PESSOA(id_pessoa)
);

CREATE TABLE CARGO_POLITICO (
  id_cargo INTEGER PRIMARY KEY AUTO_INCREMENT,
  num_id INTEGER NOT NULL,
  nome_cargo VARCHAR(50) NOT NULL,
  FOREIGN KEY(num_id) REFERENCES CANDIDATO(num_id)
);

CREATE TABLE PARTIDO (
  id_partido INTEGER PRIMARY KEY AUTO_INCREMENT,
  id_regiao INTEGER NOT NULL,
  nome_partido VARCHAR(30) NOT NULL,
  sigla VARCHAR(10) NOT NULL,
  data_fundacao DATE,
  FOREIGN KEY(id_regiao) REFERENCES REGIAO(id_regiao)
);

CREATE TABLE NOTICIA (
  noticia_id INTEGER PRIMARY KEY AUTO_INCREMENT,
  data_publicacao DATE,
  titulo_noticia VARCHAR(200) NOT NULL,
  texto VARCHAR(1000) NOT NULL
);

CREATE TABLE MIDIA (
  id_midia INTEGER PRIMARY KEY AUTO_INCREMENT,
  noticia_id INTEGER NOT NULL,
  tipo_midia VARCHAR(20) NOT NULL,
  nome_arq VARCHAR(30) NOT NULL,
  tamanho_arq INTEGER NOT NULL,
  formato_arq VARCHAR(5) NOT NULL,
  FOREIGN KEY(noticia_id) REFERENCES NOTICIA(noticia_id)
);


CREATE TABLE MEIO_COMUNICACAO(
  comunicacao_id INTEGER PRIMARY KEY AUTO_INCREMENT,
  noticia_id INTEGER NOT NULL,
  tipo_meiocom VARCHAR(20) NOT NULL,
  data_postagem DATE,
  FOREIGN KEY(noticia_id) REFERENCES NOTICIA(noticia_id)
);
